### ISSUE TITLE
displays everything

### ISSUE THREAD

**Issue by visualcookie** [jbeyerstedt/kirby-template-sitemap#3]
The sitemap displays everything, even pages, that are invisible.

**Comment by jbeyerstedt** [comment]
That’s right, but this is an intended behavior in this case.
Perhaps I should have stated it more clearly in the readme. Currently I’m only explaining, that you can set different headings for visible and invisible pages for the html version of the sitemap.

I need to show my invisible pages, which are at the top level, because the imprint and contact pages are not marked "visible". But I think, it would be useful to exclude invisible pages at the second level and lower from the sitemap. (Same behavior as the html version).
